# -*- coding: utf-8 -*-
{
    'name'          : 'Doctor Umum Antrian Pasien',
    'version'       : '0.1',
    'author'        : 'PT Arkana Solusi Bisnis',
    'license'       : 'OPL-1',
    'category'      : 'Doctor Umum Antrian Pasien',
    'website'       : 'http://www.arkana.co.id',
    'summary'       : 'Custom Doctor Umum Antrian Pasien',
    'description'   :   '''
                            Custom Doctor Umum Antrian Pasien Module for Medika
                        ''',
    'depends'       : [
                        'base',
                        'mail',
                        'portal',
                        'product',
                        'asb_klinik_doctor_team',
                        'asb_klinik_master_cost_allocation',
                        'asb_klinik_master_poli_unit',
                        'asb_klinik_master_fasilitas_kesehatan',
                        'asb_klinik_master_ketenagaan',
                        'asb_klinik_master_personil',
                        'asb_klinik_master_product',
                        'asb_klinik_costing_package',
                        'asb_klinik_costing_setting_general',
                        'asb_klinik_costing_setting_onsite',
                        'asb_klinik_admission_reservation',
                        'asb_klinik_admission_registration',
                        'asb_klinik_admission_poli_perawat',
                        'asb_master_diagnosis',
                      ],

    'data'          : [
                        'security/doctor_umum_security.xml',
                        'security/ir.model.access.csv',
                        'views/assets.xml',
                        'views/antrian_pasien_views.xml',
                        'views/plan_views.xml',
                        'views/pemeriksaan_diagnosis_views.xml',
                        'views/permintaan_lab_views.xml',
                        'views/permintaan_radiologi_views.xml',
                        'views/detail_pemeriksaan_mc_views.xml',
                        'data/plan_data.xml',
                      ],
    'installable'   : True,
    'auto_install'  : False,
    'application'   : False,
}
